version: "3.1"

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 961126
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3306:3306

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 961126
    volumes:
      - postgres:/var/lib/postgresql/data

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 961126
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db

  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.2
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data

volumes:
  mysql:
  postgres:
  mongo:
  redis:
  elasticsearch:
