version: "3.1"

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 961126
    volumes:
      - ./database/mysql:/var/lib/mysql
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOSTS: mysql
      UPLOAD_LIMIT: 2G

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 961126
      POSTGRES_DB: sonarqube
    volumes:
      - ./database/postgres:/var/lib/postgresql/data

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 961126
    ports:
      - 27017:27017
    volumes:
      - ./database/mongo:/data/db

  redis:
    image: redis
    ports:
      - 6379:6379

  sonarqube:
    image: sonarqube
    environment:
      SONARQUBE_JDBC_USERNAME: root
      SONARQUBE_JDBC_PASSWORD: 961126
      SONARQUBE_JDBC_URL: jdbc:postgresql://postgres:5432/sonarqube
    ports:
      - 9000:9000
    volumes:
      - ./sonarqube/data/:/opt/sonarqube/data
      - ./sonarqube/logs/:/opt/sonarqube/logs
      - ./sonarqube/extensions:/opt/sonarqube/extensions

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.4
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./database/es01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.4
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./database/es02:/usr/share/elasticsearch/data

  kib:
    image: docker.elastic.co/kibana/kibana:7.13.4
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: '["http://es01:9200","http://es02:9200"]'
